// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackIt.Persistance.EF.Contexts;

#nullable disable

namespace PackIt.Persistance.EF.Migrations
{
    [DbContext(typeof(WriteDbContext))]
    partial class WriteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("packing")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PackIT.Domain.ItemTypes.ItemType", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_ItemTypes_Code");

                    b.ToTable("ItemTypes", "packing");
                });

            modelBuilder.Entity("PackIT.Domain.Items.Item", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("Code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Name");

                    b.Property<long>("TypeID")
                        .HasColumnType("bigint");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Item_Code");

                    b.HasIndex("TypeID");

                    b.ToTable("Items", "packing");
                });

            modelBuilder.Entity("PackIT.Domain.Locations.Location", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)")
                        .HasColumnName("Code");

                    b.Property<string>("Description")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("Name");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("Type");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Locations_Code");

                    b.HasIndex("ParentId");

                    b.ToTable("Locations", "packing", t =>
                        {
                            t.HasCheckConstraint("CK_Location_Type_Enum", "Type IN ('Factory', 'Area', 'Line', 'Warehouse')");
                        });
                });

            modelBuilder.Entity("PackIT.Domain.Orders.OrderBase", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("BIGINT")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CreationDate");

                    b.Property<string>("Order_Type")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("int")
                        .HasColumnName("Version");

                    b.HasKey("Id");

                    b.ToTable("Orders", "packing");

                    b.HasDiscriminator<string>("Order_Type").HasValue("OrderBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PackIT.Domain.Orders.Order", b =>
                {
                    b.HasBaseType("PackIT.Domain.Orders.OrderBase");

                    b.Property<DateTime?>("DeliveryTime")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("DeliveryTime");

                    b.Property<DateTime>("RequestedDeliveryTime")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("RequestedDeliveryTime");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)")
                        .HasColumnName("Order_State");

                    b.ToTable("Orders", "packing");

                    b.HasDiscriminator().HasValue("Order");
                });

            modelBuilder.Entity("PackIT.Domain.Orders.OrderTemplate", b =>
                {
                    b.HasBaseType("PackIT.Domain.Orders.OrderBase");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.ToTable("Orders", "packing");

                    b.HasDiscriminator().HasValue("OrderTemplate");
                });

            modelBuilder.Entity("PackIT.Domain.Items.Item", b =>
                {
                    b.HasOne("PackIT.Domain.ItemTypes.ItemType", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("PackIT.Domain.Locations.Location", b =>
                {
                    b.HasOne("PackIT.Domain.Locations.Location", "ParentLocation")
                        .WithMany("Sublocations")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("PackIT.Domain.Orders.OrderBase", b =>
                {
                    b.OwnsOne("PackIT.Domain.Orders.ValueObjects.LocationVO", "RequestedDeliveryLocation", b1 =>
                        {
                            b1.Property<long>("OrderBaseId")
                                .HasColumnType("BIGINT");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("VARCHAR(30)")
                                .HasColumnName("Requested_Location_Code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("NVARCHAR(100)")
                                .HasColumnName("Requested_Location_Name");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("VARCHAR(30)")
                                .HasColumnName("Requested_Location_Type");

                            b1.HasKey("OrderBaseId");

                            b1.HasIndex("Code")
                                .HasDatabaseName("IX_Orders_Requested_Location_Code");

                            b1.ToTable("Orders", "packing");

                            b1.WithOwner()
                                .HasForeignKey("OrderBaseId");
                        });

                    b.OwnsMany("PackIT.Domain.Orders.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("Order_Id")
                                .HasColumnType("BIGINT");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.HasKey("Id");

                            b1.HasIndex("Order_Id");

                            b1.ToTable("OrderItems", "packing");

                            b1.WithOwner()
                                .HasForeignKey("Order_Id");

                            b1.OwnsOne("PackIT.Domain.Orders.ValueObjects.ItemVO", "ItemVO", b2 =>
                                {
                                    b2.Property<Guid>("OrderItemId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasColumnType("VARCHAR(30)")
                                        .HasColumnName("Item_Code");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("NVARCHAR(100)")
                                        .HasColumnName("Item_Name");

                                    b2.Property<string>("TypeCode")
                                        .IsRequired()
                                        .HasColumnType("NVARCHAR(30)")
                                        .HasColumnName("Item_TypeCode");

                                    b2.Property<string>("TypeName")
                                        .IsRequired()
                                        .HasColumnType("NVARCHAR(100)")
                                        .HasColumnName("Item_TypeName");

                                    b2.HasKey("OrderItemId");

                                    b2.HasIndex("Code")
                                        .HasDatabaseName("IX_OrderItems_ItemVO_Code");

                                    b2.ToTable("OrderItems", "packing");

                                    b2.WithOwner()
                                        .HasForeignKey("OrderItemId");
                                });

                            b1.Navigation("ItemVO")
                                .IsRequired();
                        });

                    b.Navigation("OrderItems");

                    b.Navigation("RequestedDeliveryLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("PackIT.Domain.Orders.Order", b =>
                {
                    b.OwnsOne("PackIT.Domain.Orders.ValueObjects.LocationVO", "DeliveryLocation", b1 =>
                        {
                            b1.Property<long>("OrderId")
                                .HasColumnType("BIGINT");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("VARCHAR(30)")
                                .HasColumnName("Delivery_Location_Code");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("NVARCHAR(100)")
                                .HasColumnName("Delivery_Location_Name");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasColumnType("VARCHAR(30)")
                                .HasColumnName("Delivery_Location_Type");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders", "packing");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsMany("PackIT.Domain.Orders.ValueObjects.OrderStateChangeVO", "StateChangesHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CurrentState")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("CurrentState");

                            b1.Property<DateTime>("EventTime")
                                .HasColumnType("DATETIME")
                                .HasColumnName("EventTime");

                            b1.Property<long>("OrderId")
                                .HasColumnType("BIGINT");

                            b1.Property<string>("PreviousState")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("PreviousState");

                            b1.HasKey("Id");

                            b1.HasIndex("OrderId");

                            b1.ToTable("OrderStateChangedHistory", "packing");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("DeliveryLocation");

                    b.Navigation("StateChangesHistory");
                });

            modelBuilder.Entity("PackIT.Domain.Locations.Location", b =>
                {
                    b.Navigation("Sublocations");
                });
#pragma warning restore 612, 618
        }
    }
}
